# Generated by Django 5.1.1 on 2024-09-20 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="ISBN",
            new_name="isbn",
        ),
    ]
